server:
  port: 8886

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName:  com.mysql.cj.jdbc.Driver
#    # 射击
#    url: jdbc:mysql://49.235.200.115:3306/sgame_shooting?characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: root
#    password: 4aOU2&zv
    # 射击 正式
#    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://129.204.44.23:3306/sgame_shooting?characterEncoding=utf8&useUnicode=true&useSSL=false
    url: jdbc:mysql://159.75.246.105:3306/fpsgame?characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Ty123456
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    removeAbandoned: true
    removeAbandonedTimeout: 180
    testOnBorrow: true
    maxActive: 10
    validationQuery: select 1
    poolPreparedStatements: true
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



